name: dannyfast
favicon: null
layout_spectrum: 0.956365656806156
typography_spectrum: 0.3702057381160557
title: Danny Fast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#029487'
    - '#80c9c1'
    - '#060503'
    - '#73736b'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.9642972839064896
purpose: []
